
% Add rows if necessary

% Please write in chronological order, as it will be selected in this order

% hundreds for grid + MU idx
MU_pairs = [103,201;...
    103,201;...
    101,202;...
    101,202];

unique_pairs = unique(MU_pairs,'rows','stable');

Quadrants_order = ["y";...
    "x";...
    "y";...
    "x"];

List_of_MUs_not_decomposed = {[204],...
    [204],[204],...
    [204],[204]}; % 1st cell is baseline

vars_to_save = {"MU_pairs";"Quadrants_order";"unique_pairs";"List_of_MUs_not_decomposed"};
save("Table_of_trials",vars_to_save{:});